enum enumTiles
{
    /* DIRT WITH GRASS ON TOP */
	DIRT_GRASS_CORNER_UP_LEFT =         0,  DIRT_GRASS_SIDE_UP =            31, DIRT_GRASS_CORNER_UP_RIGHT =        62, DIRT_GRASS_INNER_CORNER_RIGHT_DOWN =      93, DIRT_GRASS_INNER_CORNER_LEFT_DOWN =        124,
	DIRT_GRASS_SIDE_LEFT =              1,  DIRT_GRASS_CENTER =             32, DIRT_GRASS_SIDE_RIGHT =             63, DIRT_GRASS_INNER_CORNER_RIGHT_UP =        94, DIRT_GRASS_INNER_CORNER_LEFT_UP =          125,
	DIRT_GRASS_CORNER_DOWN_LEFT =       2,  DIRT_GRASS_SIDE_DOWN =          33, DIRT_GRASS_CORNER_DOWN_RIGHT =      64, DIRT_GRASS_A =                            95, DIRT_GRASS_C =                             126,
	DIRT_GRASS_VERTICAL =               3,  DIRT_GRASS_HORIZONTAL =         34, DIRT_GRASS_DOT =                    65, DIRT_GRASS_B =                            96, DIRT_GRASS_D =                             127,

	/* DIRT WITH DARK GRASS ON TOP */
	DIRT_DARKGRASS_CORNER_UP_LEFT =     4,  DIRT_DARKGRASS_SIDE_UP =        35, DIRT_DARKGRASS_CORNER_UP_RIGHT =    66, DIRT_DARKGRASS_INNER_CORNER_RIGHT_DOWN =  97, DIRT_DARKGRASS_INNER_CORNER_LEFT_DOWN =    128,
	DIRT_DARKGRASS_SIDE_LEFT =          5,  DIRT_DARKGRASS_CENTER =         36, DIRT_DARKGRASS_SIDE_RIGHT =         67, DIRT_DARKGRASS_INNER_CORNER_RIGHT_UP =    98, DIRT_DARKGRASS_INNER_CORNER_LEFT_UP =      129,
	DIRT_DARKGRASS_CORNER_DOWN_LEFT =   6,  DIRT_DARKGRASS_SIDE_DOWN =      37, DIRT_DARKGRASS_CORNER_DOWN_RIGHT =  68,
	DIRT_DARKGRASS_VERTICAL =           7,  DIRT_DARKGRASS_HORIZONTAL =     38, DIRT_DARKGRASS_DOT =                69,

	/* DARK GRASS WITH GRASS ON TOP */
	DARKGRASS_GRASS_CORNER_UP_LEFT =    8,  DARKGRASS_GRASS_SIDE_UP =       39, DARKGRASS_GRASS_CORNER_UP_RIGHT =   70, DARKGRASS_GRASS_INNER_CORNER_RIGHT_DOWN = 101,DARKGRASS_GRASS_INNER_CORNER_LEFT_DOWN =   132,
	DARKGRASS_GRASS_SIDE_LEFT =         9,  DARKGRASS_GRASS_CENTER =        40, DARKGRASS_GRASS_SIDE_RIGHT =        71, DARKGRASS_GRASS_INNER_CORNER_RIGHT_UP =   102,DARKGRASS_GRASS_INNER_CORNER_LEFT_UP =     133,
	DARKGRASS_GRASS_CORNER_DOWN_LEFT =  10, DARKGRASS_GRASS_SIDE_DOWN =     41, DARKGRASS_GRASS_CORNER_DOWN_RIGHT = 72,
	DARKGRASS_GRASS_VERTICAL =          11, DARKGRASS_GRASS_HORIZONTAL =    42, DARKGRASS_GRASS_DOT =               73,

	/* GRASS WITH DIRT -UNDER- */
	GRASS_DIRT_CORNER_UP_LEFT =         12, GRASS_DIRT_SIDE_UP =            43, GRASS_DIRT_CORNER_UP_RIGHT =        74, GRASS_DIRT_INNER_CORNER_RIGHT_DOWN =      105,GRASS_DIRT_INNER_CORNER_LEFT_DOWN =        136,
	GRASS_DIRT_SIDE_LEFT =              13, GRASS_DIRT_CENTER =             44, GRASS_DIRT_SIDE_RIGHT =             75, GRASS_DIRT_INNER_CORNER_RIGHT_UP =        106,GRASS_DIRT_INNER_CORNER_LEFT_UP =          137,
	GRASS_DIRT_CORNER_DOWN_LEFT =       14, GRASS_DIRT_SIDE_DOWN =          45, GRASS_DIRT_CORNER_DOWN_RIGHT =      76,
	GRASS_DIRT_VERTICAL =               15, GRASS_DIRT_HORIZONTAL =         46, GRASS_DIRT_DOT =                    77,

    /* DIRT WITH GRASS ON TOP
	DIRT_GRASS_CORNER_UP_LEFT =         0,  DIRT_GRASS_SIDE_UP =            31, DIRT_GRASS_CORNER_UP_RIGHT =        62, DIRT_GRASS_INNER_CORNER_RIGHT_DOWN =      93, DIRT_GRASS_INNER_CORNER_LEFT_DOWN =        124,
	DIRT_GRASS_SIDE_LEFT =              1,  DIRT_GRASS_CENTER =             32, DIRT_GRASS_SIDE_RIGHT =             63, DIRT_GRASS_INNER_CORNER_RIGHT_UP =        94, DIRT_GRASS_INNER_CORNER_LEFT_UP =          125,
	DIRT_GRASS_CORNER_DOWN_LEFT =       2,  DIRT_GRASS_SIDE_DOWN =          33, DIRT_GRASS_CORNER_DOWN_RIGHT =      64, DIRT_GRASS_A =                            95, DIRT_GRASS_C =                             126,
	DIRT_GRASS_VERTICAL =               3,  DIRT_GRASS_HORIZONTAL =         34, DIRT_GRASS_DOT =                    65, DIRT_GRASS_B =                            96, DIRT_GRASS_D =                             127,
*/

	/* GRASS WITH BRICKS ON TOP */
	GRASS_BRICK_CORNER_UP_LEFT =        25, GRASS_BRICK_SIDE_UP =           56, GRASS_BRICK_CORNER_UP_RIGHT =       87, GRASS_BRICK_INNER_CORNER_RIGHT_DOWN =     118,GRASS_BRICK_INNER_CORNER_LEFT_DOWN =       149,
	GRASS_BRICK_SIDE_LEFT =             26, GRASS_BRICK_CENTER =            57, GRASS_BRICK_SIDE_RIGHT =            88, GRASS_BRICK_INNER_CORNER_RIGHT_UP =       119,GRASS_BRICK_INNER_CORNER_LEFT_UP =         150,
	GRASS_BRICK_CORNER_DOWN_LEFT =      27, GRASS_BRICK_SIDE_DOWN =         58, GRASS_BRICK_CORNER_DOWN_RIGHT =     89, BRICK_LEFT =                              120,BRICK_RIGHT =                              151,

	/* GRASS WITH STONE ON TOP */
	GRASS_STONE_CORNER_UP_LEFT =        28, GRASS_STONE_SIDE_UP =           59, GRASS_STONE_CORNER_UP_RIGHT =       90, GRASS_STONE_INNER_CORNER_RIGHT_DOWN =     121,GRASS_STONE_INNER_CORNER_LEFT_DOWN =       152,
	GRASS_STONE_SIDE_LEFT =             29, GRASS_STONE_CENTER =            60, GRASS_STONE_SIDE_RIGHT =            91, GRASS_STONE_INNER_CORNER_RIGHT_UP =       122,GRASS_STONE_INNER_CORNER_LEFT_UP =         153,
	GRASS_STONE_CORNER_DOWN_LEFT =      30, GRASS_STONE_SIDE_DOWN =         61, GRASS_STONE_CORNER_DOWN_RIGHT =     92, STONE_LEFT =                              123,STONE_RIGHT =                              154,



	BG_SPRITE_TOTAL =               536
};
